#!/bin/sh

cd pipeline_manager/frontend && npm install
sed -i 's/".\/dist\/styles.css": ".\/dist\/styles.css"$/".\/dist\/styles.css": ".\/dist\/styles.css",\n    ".\/dist\/styles\/*": ".\/dist\/styles\/*"/' node_modules/@baklavajs/plugin-renderer-vue/package.json
npm run build
