#!/bin/sh

# Copyright (c) 2022-2023 Antmicro <www.antmicro.com>
#
# SPDX-License-Identifier: Apache-2.0

if [ -d "./pipeline_manager/frontend/dist" ]; then
    rm -rf "./pipeline_manager/frontend/dist"
fi

