#!/bin/sh

# Copyright (c) 2022-2023 Antmicro <www.antmicro.com>
#
# SPDX-License-Identifier: Apache-2.0

cd pipeline_manager/frontend && npm run clean
if [ -d "./dist" ]; then
    rm -rf "./dist"
fi
