#!/bin/sh

# Copyright (c) 2022-2023 Antmicro <www.antmicro.com>
#
# SPDX-License-Identifier: Apache-2.0

BASE_DIR=$(dirname "$0")

cd $BASE_DIR/pipeline_manager/frontend && npm run clean
if [ -d "./dist" ]; then
    rm -rf "./dist"
fi
if [ -f "./env.static.local" ]; then
    rm .env.static.local
fi
