#!/usr/bin/env python3

# Copyright (c) 2022-2023 Antmicro <www.antmicro.com>
#
# SPDX-License-Identifier: Apache-2.0

import sys
from pipeline_manager.__main__ import script_handler

if __name__ == '__main__':
    script_handler(sys.argv, 'validate')
